PTX_ID_LABEL: str = "PrecisionTox short identifier"
BATCH_LABEL: str = "exposure batch"
COMPOUND_LABEL: str = "compound_name"
DOSE_LABEL: str = "dose_code"
TIMEPOINT_LABEL: str = "timepoint_level"
