""" This module provide constants for the ptmd package.
"""
from .directories import (
    ROOT_PATH,
    DATA_PATH,
    DOT_ENV_CONFIG,
    GOOGLE_DRIVE_SETTINGS_FILE_PATH,
    SCHEMAS_PATH,
    INPUT_SCHEMA_PATH,
    EXPOSURE_SCHEMA_PATH,
    EXPOSURE_INFORMATION_SCHEMA_FILEPATH,
    CREATE_USER_SCHEMA_PATH,
    PARTNERS_LONGNAME_PATH,
    CHEMICALS_FILEPATH,
    ORGANISMS_FILEPATH,
    DOWNLOAD_DIRECTORY_PATH,
    CREATE_CHEMICAL_SCHEMA_PATH,
    CREATE_CHEMICALS_SCHEMA_PATH,
)
from .schema_loaders import INPUT_SCHEMA, EXPOSURE_SCHEMA, PARTNERS_LONGNAME
from .spreadsheets import (
    ALLOWED_PARTNERS,
    ALLOWED_EXPOSURE_BATCH,
    EXPOSURE_BATCH_MAX_LENGTH,
    REPLICATES_EXPOSURE_MIN,
    REPLICATES_CONTROL_MIN,
    ALLOWED_DOSE_VALUES,
    ALLOWED_VEHICLES,
    TIMEPOINTS_MIN,
    REPLICATES_BLANK_RANGE,
    DOSE_MAPPING,
    TIME_POINT_MAPPING,
    SAMPLE_SHEET_EMPTY_COLUMNS,
    SAMPLE_SHEET_COLUMNS,
    GENERAL_SHEET_COLUMNS,
    EMPTY_FIELDS_VALUES
)
from .site import SITE_URL, ADMIN_EMAIL, ADMIN_USERNAME, ADMIN_PASSWORD
from .labels import (
    PTX_ID_LABEL,
    BATCH_LABEL,
    COMPOUND_NAME_LABEL,
    DOSE_LABEL,
    TIMEPOINT_LABEL,
    COMPOUND_HASH_LABEL,
    BLANK_CODE
)

ROLES: list[str] = ['banned', 'disabled', 'enabled', 'user', 'admin']  # careful with the order
